# Generated by Django 5.0.1 on 2024-02-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Создан'), (1, 'Подтвержден'), (2, 'В обработке'), (3, 'Готов'), (4, 'В пути'), (5, 'Выдан'), (6, 'Отменен')], default=0),
        ),
    ]
