# Generated by Django 5.0.1 on 2024-02-12 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0006_basket'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Basket',
        ),
    ]
