# Generated by Django 5.0.1 on 2024-02-09 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_archived',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Архивирован'),
        ),
        migrations.AddField(
            model_name='user',
            name='verified_email',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Подтвержденная почта'),
        ),
    ]
