# Generated by Django 5.0.1 on 2024-02-12 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_alter_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(blank=True, null=True, unique=True, verbose_name='Код подтверждения')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создан')),
                ('expired', models.DateTimeField(blank=True, null=True, verbose_name='Действует до')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Подтверждение почты',
                'verbose_name_plural': 'Подтверждения почты',
                'db_table': 'email_verifications',
                'ordering': ['created'],
            },
        ),
    ]
